#include QMK_KEYBOARD_H

#ifdef FLASH_KEYMAP_COUNT
const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
  {
    {KC_ESCAPE, KC_BSPACE, KC_LSHIFT, KC_TAB},
    {KC_NUMLOCK, KC_EQUAL, KC_KP_ASTERISK, KC_KP_SLASH},
    {KC_KP_7, KC_KP_MINUS, KC_KP_9, KC_KP_8},
    {KC_KP_4, KC_KP_PLUS, KC_KP_6, KC_KP_5},
    {KC_KP_1, KC_KP_ENTER, KC_KP_3, KC_KP_2},
    {KC_KP_0, KC_TRNS, KC_KP_DOT, USER13}
  },
  {
    {KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS},
    {KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS},
    {KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS},
    {KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS},
    {KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS},
    {KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS}
  },
};
#else
const uint8_t PROGMEM keymaps8[][MATRIX_ROWS][MATRIX_COLS] =
{
  {
    {KC_ESCAPE, KC_BSPACE, KC_LSHIFT, KC_TAB},
    {KC_NUMLOCK, KC_KP_EQUAL, KC_KP_ASTERISK, KC_KP_SLASH},
    {KC_KP_7, KC_KP_MINUS, KC_KP_9, KC_KP_8},
    {KC_KP_4, KC_KP_PLUS, KC_KP_6, KC_KP_5},
    {KC_KP_1, KC_KP_ENTER, KC_KP_3, KC_KP_2},
    {KC_KP_0, KC_TRNS, KC_KP_DOT, KC_TRNS}
  },
};

#endif


