#include QMK_KEYBOARD_H

enum user_keycode {
    BT_USB = USER00, 
    KB_RESET, 
    BATT_LEVEL, 
    LOCK_MODE, 
    RGB_Toogle, 
    RGB_Mode_DN, 
    RGB_Mode_UP, 
    RGB_HUE_DN, 
    RGB_HUE_UP, 
    RGB_SAT_DN, 
    RGB_SAT_UP, 
    RGB_LUM_DN, 
    RGB_LUM_UP, 
};

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
  [0] = {
    {KC_GESC, KC_2, KC_1, KC_3, KC_4, KC_5, KC_6, KC_7, KC_8, KC_9, KC_0, KC_MINUS, KC_EQUAL, KC_BSPACE, KC_HOME, KC_VOLD}, 
    {KC_TAB, KC_Q, KC_W, KC_E, KC_R, KC_T, KC_Y, KC_U, KC_I, KC_O, KC_P, KC_LBRACKET, KC_RBRACKET, KC_BSLASH, KC_PGUP, KC_VOLU}, 
    {KC_CAPSLOCK, KC_A, KC_S, KC_D, KC_F, KC_G, KC_H, KC_NO, KC_J, KC_K, KC_L, KC_SCOLON, KC_QUOTE, KC_ENTER, KC_PGDOWN, KC_END}, 
    {KC_LSHIFT, KC_Z, KC_X, KC_C, KC_V, KC_LCTRL, KC_LGUI, KC_LALT, KC_M, KC_COMMA, KC_DOT, KC_N, KC_B, KC_SLASH, KC_RSHIFT, KC_UP}, 
    {KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_SPACE, KC_NO, KC_RALT, MO(1), KC_MUTE, KC_LEFT, KC_DOWN, KC_RIGHT}

	}, 
  [1] = {
    {KC_GRAVE, KC_F2, KC_F1, KC_F3, KC_F4, KC_F5, KC_F6, KC_F7, KC_F8, KC_F9, KC_F10, KC_F11, KC_F12, KC_DELETE, KC_TRNS, KC_TRNS}, 
    {KC_TRNS, KC_BTN1, KC_MS_U, KC_BTN2, RGB_Toogle, RGB_Mode_UP, KC_BRID, KC_BRIU, KC_PSCREEN, KC_SCROLLLOCK, KC_PAUSE, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS}, 
    {KC_TRNS, KC_MS_L, KC_MS_D, KC_MS_R, RGB_HUE_UP, RGB_SAT_UP, RGB_LUM_UP, KC_NO, KC_TRNS, KC_HOME, KC_PGUP, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS}, 
    {KC_TRNS, KC_TRNS, KC_TRNS, KC_CALC, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_END, KC_PGDOWN, KC_TRNS, KB_RESET, KC_TRNS, KC_TRNS, KC_TRNS}, 
    {KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_TRNS, KC_NO, KC_TRNS, KC_TRNS, KC_TRNS, KC_MPRV, KC_MPLY, KC_MNXT}
	}, 

};
